version: "3.3"

services:
  elasticsearch:
      image: elastic/elasticsearch:6.3.2

  kibana:
      image: elastic/kibana:6.3.2
    ports:
      - "8080:80"
    depends_on:
        - elasticsearch

  server:
      image: golang:alpine
      workdir: /go/src/github.com/wiltongarcia/studp/
      command: make server
      volumes:
          - "./:/go/src/github.com/wiltongarcia/studp/" 
      depends_on:
          - elasticsearch

  client:
      image: golang:alpine
      workdir: /go/src/github.com/wiltongarcia/studp/client/
      command: make client
      volumes:
          - "./client:/go/src/github.com/wiltongarcia/studp/client" 
      depends_on:
          - server
